# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'cardapio.ui'
##
## Created by: Qt User Interface Compiler version 6.8.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QFrame, QLabel,
    QMainWindow, QMenuBar, QPushButton, QSizePolicy,
    QStatusBar, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(800, 578)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.cardapio = QFrame(self.centralwidget)
        self.cardapio.setObjectName(u"cardapio")
        self.cardapio.setGeometry(QRect(10, -10, 781, 541))
        self.cardapio.setStyleSheet(u"background-color: rgb(230, 232, 212);")
        self.cardapio.setFrameShape(QFrame.Shape.StyledPanel)
        self.cardapio.setFrameShadow(QFrame.Shadow.Raised)
        self.lanches = QLabel(self.cardapio)
        self.lanches.setObjectName(u"lanches")
        self.lanches.setGeometry(QRect(20, 40, 121, 31))
        font = QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.lanches.setFont(font)
        self.lanches.setStyleSheet(u"background-color: rgb(195, 72, 41);")
        self.lanches_lista = QComboBox(self.cardapio)
        self.lanches_lista.addItem("")
        self.lanches_lista.addItem("")
        self.lanches_lista.addItem("")
        self.lanches_lista.addItem("")
        self.lanches_lista.addItem("")
        self.lanches_lista.addItem("")
        self.lanches_lista.setObjectName(u"lanches_lista")
        self.lanches_lista.setGeometry(QRect(20, 90, 111, 31))
        self.lanches_lista.setStyleSheet(u"background-color: rgb(187, 214, 68);")
        self.adicionar_produto = QPushButton(self.cardapio)
        self.adicionar_produto.setObjectName(u"adicionar_produto")
        self.adicionar_produto.setGeometry(QRect(160, 283, 131, 41))
        self.adicionar_produto.setStyleSheet(u"background-color: rgb(252, 168, 56);")
        self.total = QLabel(self.cardapio)
        self.total.setObjectName(u"total")
        self.total.setGeometry(QRect(330, 420, 131, 61))
        font1 = QFont()
        font1.setPointSize(14)
        font1.setBold(True)
        self.total.setFont(font1)
        self.total.setStyleSheet(u"background-color: rgb(172, 47, 29);\n"
"color: rgb(255, 255, 255);")
        self.finalizar_produto = QPushButton(self.cardapio)
        self.finalizar_produto.setObjectName(u"finalizar_produto")
        self.finalizar_produto.setGeometry(QRect(450, 283, 111, 41))
        self.finalizar_produto.setStyleSheet(u"background-color: rgb(252, 168, 56);")
        self.Bebidas = QLabel(self.cardapio)
        self.Bebidas.setObjectName(u"Bebidas")
        self.Bebidas.setGeometry(QRect(408, 45, 61, 31))
        self.Bebidas.setFont(font)
        self.Bebidas.setStyleSheet(u"background-color: rgb(195, 72, 41);")
        self.Acompanhamentos = QLabel(self.cardapio)
        self.Acompanhamentos.setObjectName(u"Acompanhamentos")
        self.Acompanhamentos.setGeometry(QRect(600, 45, 151, 31))
        self.Acompanhamentos.setFont(font)
        self.Acompanhamentos.setStyleSheet(u"background-color: rgb(195, 72, 41);")
        self.Adicionais = QLabel(self.cardapio)
        self.Adicionais.setObjectName(u"Adicionais")
        self.Adicionais.setGeometry(QRect(210, 45, 91, 31))
        self.Adicionais.setFont(font)
        self.Adicionais.setStyleSheet(u"background-color: rgb(195, 72, 41);")
        self.adicionais_lista = QComboBox(self.cardapio)
        self.adicionais_lista.addItem("")
        self.adicionais_lista.addItem("")
        self.adicionais_lista.addItem("")
        self.adicionais_lista.addItem("")
        self.adicionais_lista.addItem("")
        self.adicionais_lista.setObjectName(u"adicionais_lista")
        self.adicionais_lista.setGeometry(QRect(220, 90, 91, 31))
        self.adicionais_lista.setStyleSheet(u"background-color: rgb(187, 214, 68);")
        self.Bebidas_Lista = QComboBox(self.cardapio)
        self.Bebidas_Lista.addItem("")
        self.Bebidas_Lista.addItem("")
        self.Bebidas_Lista.addItem("")
        self.Bebidas_Lista.addItem("")
        self.Bebidas_Lista.addItem("")
        self.Bebidas_Lista.addItem("")
        self.Bebidas_Lista.addItem("")
        self.Bebidas_Lista.setObjectName(u"Bebidas_Lista")
        self.Bebidas_Lista.setGeometry(QRect(380, 91, 151, 31))
        self.Bebidas_Lista.setStyleSheet(u"background-color: rgb(187, 214, 68);")
        self.Acompanha_lista = QComboBox(self.cardapio)
        self.Acompanha_lista.addItem("")
        self.Acompanha_lista.addItem("")
        self.Acompanha_lista.addItem("")
        self.Acompanha_lista.addItem("")
        self.Acompanha_lista.setObjectName(u"Acompanha_lista")
        self.Acompanha_lista.setGeometry(QRect(620, 90, 101, 31))
        self.Acompanha_lista.setStyleSheet(u"background-color: rgb(187, 214, 68);")
        self.icone_lance = QLabel(self.cardapio)
        self.icone_lance.setObjectName(u"icone_lance")
        self.icone_lance.setGeometry(QRect(40, 470, 31, 31))
        self.icone_lance.setPixmap(QPixmap(u"../../Lanchonete/lanche.png"))
        self.icone_lance.setScaledContents(True)
        self.icone_lance_2 = QLabel(self.cardapio)
        self.icone_lance_2.setObjectName(u"icone_lance_2")
        self.icone_lance_2.setGeometry(QRect(100, 340, 31, 31))
        self.icone_lance_2.setPixmap(QPixmap(u"../../Lanchonete/lanche.png"))
        self.icone_lance_2.setScaledContents(True)
        self.icone_lance_3 = QLabel(self.cardapio)
        self.icone_lance_3.setObjectName(u"icone_lance_3")
        self.icone_lance_3.setGeometry(QRect(450, 230, 31, 31))
        self.icone_lance_3.setPixmap(QPixmap(u"../../Lanchonete/lanche.png"))
        self.icone_lance_3.setScaledContents(True)
        self.icone_lance_4 = QLabel(self.cardapio)
        self.icone_lance_4.setObjectName(u"icone_lance_4")
        self.icone_lance_4.setGeometry(QRect(620, 260, 31, 31))
        self.icone_lance_4.setPixmap(QPixmap(u"../../Lanchonete/lanche.png"))
        self.icone_lance_4.setScaledContents(True)
        self.icone_lance_5 = QLabel(self.cardapio)
        self.icone_lance_5.setObjectName(u"icone_lance_5")
        self.icone_lance_5.setGeometry(QRect(310, 270, 31, 31))
        self.icone_lance_5.setPixmap(QPixmap(u"../../Lanchonete/lanche.png"))
        self.icone_lance_5.setScaledContents(True)
        self.icone_lance_6 = QLabel(self.cardapio)
        self.icone_lance_6.setObjectName(u"icone_lance_6")
        self.icone_lance_6.setGeometry(QRect(80, 180, 31, 31))
        self.icone_lance_6.setPixmap(QPixmap(u"../../Lanchonete/lanche.png"))
        self.icone_lance_6.setScaledContents(True)
        self.icone_lance_7 = QLabel(self.cardapio)
        self.icone_lance_7.setObjectName(u"icone_lance_7")
        self.icone_lance_7.setGeometry(QRect(250, 180, 31, 31))
        self.icone_lance_7.setPixmap(QPixmap(u"../../Lanchonete/lanche.png"))
        self.icone_lance_7.setScaledContents(True)
        self.icone_lance_8 = QLabel(self.cardapio)
        self.icone_lance_8.setObjectName(u"icone_lance_8")
        self.icone_lance_8.setGeometry(QRect(670, 200, 31, 31))
        self.icone_lance_8.setPixmap(QPixmap(u"../../Lanchonete/lanche.png"))
        self.icone_lance_8.setScaledContents(True)
        self.icone_lance_9 = QLabel(self.cardapio)
        self.icone_lance_9.setObjectName(u"icone_lance_9")
        self.icone_lance_9.setGeometry(QRect(700, 430, 31, 31))
        self.icone_lance_9.setPixmap(QPixmap(u"../../Lanchonete/lanche.png"))
        self.icone_lance_9.setScaledContents(True)
        self.icone_lance_10 = QLabel(self.cardapio)
        self.icone_lance_10.setObjectName(u"icone_lance_10")
        self.icone_lance_10.setGeometry(QRect(560, 420, 31, 31))
        self.icone_lance_10.setPixmap(QPixmap(u"../../Lanchonete/lanche.png"))
        self.icone_lance_10.setScaledContents(True)
        self.icone_lance_11 = QLabel(self.cardapio)
        self.icone_lance_11.setObjectName(u"icone_lance_11")
        self.icone_lance_11.setGeometry(QRect(530, 180, 31, 31))
        self.icone_lance_11.setPixmap(QPixmap(u"../../Lanchonete/lanche.png"))
        self.icone_lance_11.setScaledContents(True)
        self.icone_lance_12 = QLabel(self.cardapio)
        self.icone_lance_12.setObjectName(u"icone_lance_12")
        self.icone_lance_12.setGeometry(QRect(250, 450, 31, 31))
        self.icone_lance_12.setPixmap(QPixmap(u"../../Lanchonete/lanche.png"))
        self.icone_lance_12.setScaledContents(True)
        self.icone_lance_13 = QLabel(self.cardapio)
        self.icone_lance_13.setObjectName(u"icone_lance_13")
        self.icone_lance_13.setGeometry(QRect(30, 260, 31, 31))
        self.icone_lance_13.setPixmap(QPixmap(u"../../Lanchonete/lanche.png"))
        self.icone_lance_13.setScaledContents(True)
        self.icone_lance_14 = QLabel(self.cardapio)
        self.icone_lance_14.setObjectName(u"icone_lance_14")
        self.icone_lance_14.setGeometry(QRect(400, 180, 31, 31))
        self.icone_lance_14.setPixmap(QPixmap(u"../../Lanchonete/lanche.png"))
        self.icone_lance_14.setScaledContents(True)
        self.icone_lance_15 = QLabel(self.cardapio)
        self.icone_lance_15.setObjectName(u"icone_lance_15")
        self.icone_lance_15.setGeometry(QRect(390, 370, 31, 31))
        self.icone_lance_15.setPixmap(QPixmap(u"../../Lanchonete/lanche.png"))
        self.icone_lance_15.setScaledContents(True)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 800, 22))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.lanches.setText(QCoreApplication.translate("MainWindow", u"Lanches", None))
        self.lanches_lista.setItemText(0, QCoreApplication.translate("MainWindow", u"x-salada", None))
        self.lanches_lista.setItemText(1, QCoreApplication.translate("MainWindow", u"x-calabresa", None))
        self.lanches_lista.setItemText(2, QCoreApplication.translate("MainWindow", u"x-bacon", None))
        self.lanches_lista.setItemText(3, QCoreApplication.translate("MainWindow", u"x-tudo", None))
        self.lanches_lista.setItemText(4, QCoreApplication.translate("MainWindow", u"x-egg", None))
        self.lanches_lista.setItemText(5, QCoreApplication.translate("MainWindow", u"x-guloso", None))

        self.adicionar_produto.setText(QCoreApplication.translate("MainWindow", u"Adicionar Produto", None))
        self.total.setText(QCoreApplication.translate("MainWindow", u"Total: R$ 0.00", None))
        self.finalizar_produto.setText(QCoreApplication.translate("MainWindow", u"Finalizar Pedido", None))
        self.Bebidas.setText(QCoreApplication.translate("MainWindow", u"Bebidas", None))
        self.Acompanhamentos.setText(QCoreApplication.translate("MainWindow", u"Acompanhamentos", None))
        self.Adicionais.setText(QCoreApplication.translate("MainWindow", u"Adicionais", None))
        self.adicionais_lista.setItemText(0, QCoreApplication.translate("MainWindow", u"Calabresa", None))
        self.adicionais_lista.setItemText(1, QCoreApplication.translate("MainWindow", u"Bacon", None))
        self.adicionais_lista.setItemText(2, QCoreApplication.translate("MainWindow", u"Cebola", None))
        self.adicionais_lista.setItemText(3, QCoreApplication.translate("MainWindow", u"Catupry", None))
        self.adicionais_lista.setItemText(4, QCoreApplication.translate("MainWindow", u"tomate", None))

        self.Bebidas_Lista.setItemText(0, QCoreApplication.translate("MainWindow", u"suco de laranja natural", None))
        self.Bebidas_Lista.setItemText(1, QCoreApplication.translate("MainWindow", u"suco de polpa", None))
        self.Bebidas_Lista.setItemText(2, QCoreApplication.translate("MainWindow", u"agua com g\u00e1s", None))
        self.Bebidas_Lista.setItemText(3, QCoreApplication.translate("MainWindow", u"coca-cola", None))
        self.Bebidas_Lista.setItemText(4, QCoreApplication.translate("MainWindow", u"fanta", None))
        self.Bebidas_Lista.setItemText(5, QCoreApplication.translate("MainWindow", u"sprite", None))
        self.Bebidas_Lista.setItemText(6, QCoreApplication.translate("MainWindow", u"cerveja", None))

        self.Acompanha_lista.setItemText(0, QCoreApplication.translate("MainWindow", u"Batata Frita", None))
        self.Acompanha_lista.setItemText(1, QCoreApplication.translate("MainWindow", u"Batata Frita Porreta", None))
        self.Acompanha_lista.setItemText(2, QCoreApplication.translate("MainWindow", u"Por\u00e7\u00e3o Calabresa", None))
        self.Acompanha_lista.setItemText(3, QCoreApplication.translate("MainWindow", u"Por\u00e7\u00e3o Onions", None))

        self.icone_lance.setText("")
        self.icone_lance_2.setText("")
        self.icone_lance_3.setText("")
        self.icone_lance_4.setText("")
        self.icone_lance_5.setText("")
        self.icone_lance_6.setText("")
        self.icone_lance_7.setText("")
        self.icone_lance_8.setText("")
        self.icone_lance_9.setText("")
        self.icone_lance_10.setText("")
        self.icone_lance_11.setText("")
        self.icone_lance_12.setText("")
        self.icone_lance_13.setText("")
        self.icone_lance_14.setText("")
        self.icone_lance_15.setText("")
    # retranslateUi
if __name__ == "__main__":
    import sys
    app = QApplication(sys.argv)
    MainWindow = QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
